name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # triggers only on tags like v1 or v1.0.0

env:
  DOCKER_REPO: sanchalkhedkar/asas

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sanchalkhedkar
          password: dckr_pat_yC7BqB9FPf8d_ZT9M_A4dktjrWo

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ env.VERSION }}
            ${{ env.DOCKER_REPO }}:latest  # Remove this line if you don’t want `latest`
          labels: |
            version=${{ env.VERSION }}
            description="Docker image for Angular application"

      - name: Output pushed image info
        run: |
            echo "Pushed image: ${{ env.DOCKER_REPO }}:${{ env.VERSION }}"
