name: Build and Push Docker Image
on:
 push:
  branches: [main]
  tags: 
    - 'frontend-*.*.*'
   
env:
   DOCKER_REPO: sanchalkhedkar/asas

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version
        run: |
       
           TAG_NAME=${GITHUB_REF#refs/tags/}        # frontend-1.0.0
           VERSION=${TAG_NAME#frontend-}            # 1.0.0
           APP_VERSION="frontend-$VERSION"          # frontend-1.0.0
           echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV




      - name: Log in to DockerHub
        run: echo "dckr_pat_yC7BqB9FPf8d_ZT9M_A4dktjrWo" | docker login -u "sanchalkhedkar" --password-stdin

      - name: Build and tag Docker image
        run: |
           docker build -t $DOCKER_REPO:$APP_VERSION .
           echo "Image tagged as: $DOCKER_REPO:$APP_VERSION"

      - name: Push Docker image
        run: |
          docker push $DOCKER_REPO:$APP_VERSION
         # docker push $DOCKER_REPO:latest
