name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  

env:
  DOCKER_REPO: sanchalkhedkar/asas

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sanchalkhedkar
          password: dckr_pat_yC7BqB9FPf8d_ZT9M_A4dktjrWo
      
      - name: Extract Docker metadata
        id: version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Extracted version: $VERSION"
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV


      - name: Build tag for docker  image
        run: |
          docker build -t your-docker-repo/your-image-name:${{ env.APP_VERSION }} .
          docker tag your-docker-repo/your-image-name:${{ env.APP_VERSION }} your-docker-repo/your-image-name:latest


      - name: Push Docker image
        run: |
           docker push $DOCKER_REPO:$APP_VERSION
           docker push $DOCKER_REPO:latest
      
      - name: Output pushed image info
        run: |
              echo "Image pushed with tags: ${{ steps.meta.outputs.tags }}"
