name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Trigger on version tags

env:
  DOCKER_REPO: sanchalkhedkar/asas

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version from tag
        id: set_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sanchalkhedkar
          password: dckr_pat_yC7BqB9FPf8d_ZT9M_A4dktjrWo

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ env.VERSION }}  # Tag with the version from the Git tag
            ${{ env.DOCKER_REPO }}:latest  # Optionally tag with latest
          labels: |
            version=${{ env.VERSION }}
            description="Docker image for Angular application"

      - name: Output pushed image info
        run: |
          echo "Image pushed: ${{ env.DOCKER_REPO }}:${{ env.VERSION }}"
